### ISSUE TITLE
Undefined array key "doktype"

### ISSUE THREAD

**Issue by davsalv** [TYPO3GmbH/blog#260] opened 2022-10-20 10:52 UTC
Whenever calling a page I get this error in the logs:

PHP Warning: Undefined array key "doktype" in typo3conf/ext/blog/Classes/ExpressionLanguage/BlogVariableProvider.php line 26

Is it possible to resolve this error?

**Comment by SchoolGuy** [comment] 2022-10-25 20:53
I am having a similar issue with version 11.0.2.

```
 TYPO3 Version 11.5.17
Webserver Apache/2.4.38 (Debian)
PHP Version 8.0.24
Database (Default) MySQL 10.6.10-MariaDB
Application Context Production
Operating System Linux 5.17.4-1-default
Bootstrap Package 12.0.5 
```

**Comment by SchoolGuy** [comment] 2022-10-25 20:55
This should be duplicate of #245

**Closed** 2022-11-22 09:19 UTC
